# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=movies_user
      - POSTGRES_PASSWORD=movies_api
      - POSTGRES_DB=movies
    ports:
      - '5432:5432'
